### ISSUE TITLE
 419 Page Expired

### ISSUE THREAD

**Issue by toddlyons** [LinkStackOrg/LinkStack#428]
After entering every / single / new / link / ... 
I get a "419 | Page Expired" and I have to login again.

Brand new install (15 minutes ago) under my website. Was unzipped on the server.

**Comment by JulianPrieber** [comment]
Please provide details about your system:

Platform: `Ubuntu 22.04 LTS`
Server type: `NGINX/Apache2 ...`
PHP version: `8.1`

**Comment by toddlyons** [comment]
Shared hosting. No idea. I run two dozen websites on it and this is the only software that doesn't work. 

I am currently using LittleLink Custom which was forked from your original project.

**Comment by JulianPrieber** [comment]
Some hosting providers do not work well with this application.
This project is LittleLink Custom, just with a new name.

If you installed it 15 minutes ago you should be already using LinkStack nothing that says LittleLink Custom.

Do you get any errors in your browser console?

**Comment by toddlyons** [comment]
Yes, it does say LinkStack, and yes... my console is full of red "attribute_error: normandy.request_time" notifications.

**Comment by JulianPrieber** [comment]
You may have to disable your ad blocker or No script. Maybe try to reproduce this in another browser, preferably in an incognito tab.

**Comment by toddlyons** [comment]
So, it works perfectly in a private window. _However_, my ad blocker, uBlock Origin, is set to run in private windows and is still active (just verified).

So, it's not just the adblocker.

**Comment by toddlyons** [comment]
Weirdly enough, it was Secure Password Generator that seemed to cause the conflict. Firefox now has its own built-in password generator, so the plugin is superfluous. But just for the record:

https://addons.mozilla.org/en-CA/firefox/addon/secure-password-generator/

**Comment by Crebbits** [comment]
I'm having this issue as well but not using any extensions on a clean Firefox and Safari
The Firefox console says:
`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/`

and Safari console says: `[Warning] [blocked] The page at https://domain.com/studio/add-link was not allowed to display insecure content from http://perrychen.xyz/studio/linkparamform_part/1/0. (libs.min.js, line 25) `

`[Error] XMLHttpRequest cannot load http://domain.com/studio/linkparamform_part/1/0 due to access control checks.

	send (libs.min.js:25:79469)
	ajax (libs.min.js:25:75035)
	(anonymous function) (libs.min.js:25:81826)
	LoadLinkTypeParams (add-link:886:149)
	(anonymous function) (add-link:872)
	c (libs.min.js:25:26510)
	(anonymous function) (libs.min.js:25:26808)`

**Comment by toddlyons** [comment]
Hmm. For the record, I'm still experiencing a failure of the software to make a cookie for the "Remember Me" login checkbox, which is apparently a related/duplicate issue. So, I still have to login every time, but not after every change action like before.

**Comment by JulianPrieber** [comment]
@Crebbits unrelated issue. This has been covered a lot on the Docker repository.

If you need help with that you can start a discussion here: https://github.com/LinkStackOrg/LinkStack/discussions/categories/issues
Or here for the docker version:
https://github.com/LinkStackOrg/linkstack-docker/discussions/categories/issues

**Comment by Leopere** [comment]
This is still a problem now; not sure why it's a closed issue when it's consistently a problem in browsers.  The only way I can edit the links list is via the De-googled version of the Chromium browser with almost no addons that I use begrudgingly because my work's browser extensions only work on a Chromium base.
