### ISSUE TITLE
Threads icon is not available

### ISSUE THREAD

**Issue by SkfyZ** [LinkStackOrg/LinkStack#539]
Please adapt the latest icons

https://fontawesome.com/icons/threads?f=brands&s=solid

**Comment by Loweack** [comment]
Hello 👋,

I also wanted different new logos (Threads and X), so I decided to do some "reverse engineering" to fix the issue.
In the end, the problem is that the Font Awesome files from LinkStack are not really up to date.

Here's what I did : 
1. Downloaded the latest "Free for web" version of Font Awesome >> [https://fontawesome.com/download](https://fontawesome.com/download)
2. Extracted some files:
	a. The folder "webfonts" with its 8 font files
	b. "all.js" in the folder "js" (that needs to be renamed "fontawesome.js")
	c. "all.css" in the folder "css" (that needs to be renamed "fontawesome.css")
3. Copied/Replaced the previously extracted files in the following folders (via FTP) :
	a. 8 font files from "webfonts" go to : "assets/webfonts" and "studio/webfonts"
	b. "fontawesome.js" and "fontawesome.css" go to "assets/external-dependencies"
	
You can then create a new link in the "Link" section and select the block "Custom Link".
Once created, you'll be able to customize it by adding some custom icons from Font Awesome (for example, "fa-brands fa-threads" for Threads or "fa-brands fa-x-twitter" for X).

I hope it helped you 🙂

**Comment by JulianPrieber** [comment]
https://github.com/LinkStackOrg/LinkStack/tree/main/assets/external-dependencies
https://github.com/LinkStackOrg/LinkStack/blob/main/assets/external-dependencies/fontawesome.css
https://github.com/LinkStackOrg/LinkStack/blob/main/assets/external-dependencies/fontawesome.js

**Comment by SkfyZ** [comment]
> 你好👋，
> 
> 我还想要不同的新徽标（Threads 和 X），因此我决定进行一些“逆向工程”来解决该问题。 最后，问题是 LinkStack 中的 Font Awesome 文件并不是真正最新的。
> 
> 这就是我所做的：
> 
> 1. 下载最新的“免费网络”版本的 Font Awesome >> https://fontawesome.com/download
> 2. 提取一些文件
>    ：文件夹“webfonts”及其 8 个字体文件
>    b．
>    文件夹“ js”中的“all.js”（需要重命名为“fontawesome.js”）“css”文件夹中的“all.css”（需要重命名为“fontawesome.css”）
> 3. 复制/替换以下文件夹中先前提取的文件（通过 FTP）
>    ：
>    b.来自“webfonts”的 8 个字体文件转到：“assets/webfonts”和“studio/webfonts” “fontawesome.js”和“fontawesome.css”转到“资产/外部依赖项”
> 
> 然后，您可以在“链接”部分中创建一个新链接并选择“自定义链接”块。 创建后，您将能够通过添加 Font Awesome 中的一些自定义图标来对其进行自定义（例如，对于 Threads 为“fa-brands fa-threads”，对于 X 为“fa-brands fa-x-twitter”）。
> 
> 我希望它对你有帮助 回复
> 
> 结果可以在这里看到>> https://www.loweack.com/

it's work,thank you

**Comment by arnehm2000** [comment]
same for bluesky

**Comment by Loweack** [comment]
Could it be possible to update the files mentionned on my previous post inside the next release?

**Comment by MattDevTec** [comment]
> Please adapt the latest icons
> 
> https://fontawesome.com/icons/threads?f=brands&s=solid

@eyax-futa I have seen that threads still has not been added, I am working on adding it myself and making a pull request to implement it.
