### ISSUE TITLE
Can't update Linkstack

### ISSUE THREAD

**Issue by FuckingToasters** [LinkStackOrg/LinkStack#633]
### LinkStack version

4.4.0

### Description

I want to update to 4.4.1 but the manual update process causes an issue as shown on the screenshot attached.
Manually updating (placing changed files in the directory) don't update anything aswell.

![growing gigantic porcupine](https://github.com/LinkStackOrg/LinkStack/assets/94435104/21b9de90-ede8-46a3-a2be-b0f64f9de9cb)

The Error don't show much Informations about the error i can't be more specific about the error which caused this.

### Details about your system

Debian 11
Docker version 24.0.7, build afdd53b
PHP 8.2.7
System Linux linkstack 5.4.114-1-pve #1 SMP PVE 5.4.114-1 (Sun, 09 May 2021 17:13:05 +0200) x86_64 

### How to reproduce

Try to update version 4.4.0 to 4.4.1

**Comment by JulianPrieber** [comment]
This error can only appear for two reasons:
A: You have some sort of permission issue in your file system.
B: Your version number in version.json is the same as one of the latest release.

**Comment by simonives** [comment]
Or user may be using a cache that is displaying cached files in their web browser.On 26 Nov 2023, at 11:48 pm, Julian Prieber ***@***.***> wrote:﻿
This error can only appear for two reasons:
A: You have some sort of permission issue in your file system.
B: Your version number in version.json is the same as one of the latest release.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**************************************This email is from SimonIves.com based in Australia.Please delete this email if you are not the intended recipient.**************************************
